# Generated by Django 4.2.2 on 2026-09-18 13:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_company_email_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=users.models.user_profile_pic_path),
        ),
    ]
