# Generated by Django 4.2.2 on 2026-09-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_completed_tour',
            field=models.BooleanField(default=False),
        ),
    ]
