# Generated by Django 4.2.2 on 2026-09-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0017_globalsettings_language_switcher_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_survey_subject', models.CharField(default='Jums priskirta nauja apklausa', help_text='El. laiško tema, kai vartotojui priskiriama nauja apklausa.', max_length=255)),
                ('new_survey_body', models.TextField(default='Sveiki,\n\nJums buvo priskirta nauja apklausa. Prašome prisijungti prie OrbiGrow platformos ir užpildyti apklausą.\n\nPagarbiai,\nOrbiGrow komanda', help_text='El. laiško tekstas, siunčiamas vartotojui, kai jam priskiriama nauja apklausa.')),
                ('survey_request_subject', models.CharField(default='Gautas naujas prašymas užpildyti apklausą', help_text='El. laiško tema, kai gaunamas prašymas užpildyti apklausą.', max_length=255)),
                ('survey_request_body', models.TextField(default='Sveiki,\n\nGavote naują prašymą užpildyti apklausą. Prašome prisijungti prie OrbiGrow platformos ir peržiūrėti prašymą.\n\nPagarbiai,\nOrbiGrow komanda', help_text='El. laiško tekstas, siunčiamas vartotojui, kai gaunamas prašymas apklausai.')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
    ]
