# Generated by Django 4.2.2 on 2026-09-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0018_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedescription',
            name='home_hero_desc',
            field=models.TextField(default='Pasirinkite raktinius žodžius, pridėkite komentarą — sistema per kelias sekundes pavers tai aiškiu, į augimą orientuotu grįžtamuoju ryšiu.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='home_hero_desc_en',
            field=models.TextField(blank=True, default='Select keywords, add a comment — the system will turn it into clear, growth-oriented feedback in seconds.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='home_hero_title',
            field=models.CharField(default='Jūs jau žinote. Mes tiesiog randame žodžius.', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='home_hero_title_en',
            field=models.CharField(blank=True, default='You already know. We just find the words.', max_length=255),
        ),
    ]
