# Generated by Django 4.2.2 on 2026-09-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0019_add_home_hero_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='feedback_received_body',
            field=models.TextField(default='Sveiki, {vardas}!\n\nJūsų kolega {vertintojas} pateikė atsiliepimą apie jus.\nPrisijunkite prie OrbiGrow platformos ir peržiūrėkite gautą grįžtamąjį ryšį.\n\nPagarbiai,\nOrbiGrow komanda', help_text='El. laiško tekstas, siunčiamas darbuotojui, kai jis gauna įvertinimą.'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='feedback_received_subject',
            field=models.CharField(default='Gavote naują įvertinimą', help_text='El. laiško tema, kai darbuotojas gauna įvertinimą.', max_length=255),
        ),
    ]
