# Generated by Django 4.2.2 on 2026-09-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0020_add_feedback_received_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='employee_comment',
            field=models.TextField(blank=True, help_text='Atsiliepimą gavusio darbuotojo komentaras/refleksija', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='employee_comment_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
