# Generated by Django 4.2.2 on 2026-09-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0021_feedback_employee_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Pagrindinė antraštė (LT)', max_length=255)),
                ('title_en', models.CharField(blank=True, help_text='Pagrindinė antraštė (EN)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Papildomas aprašymas po antrašte (LT)')),
                ('description_en', models.TextField(blank=True, help_text='Papildomas aprašymas po antrašte (EN)')),
                ('button_text', models.CharField(blank=True, help_text='Mygtuko tekstas (LT). Palikite tuščią jei nenorima mygtuko.', max_length=100)),
                ('button_text_en', models.CharField(blank=True, help_text='Mygtuko tekstas (EN)', max_length=100)),
                ('button_url', models.CharField(blank=True, help_text='Nuoroda, kur veda mygtukas (pvz. /results/ arba https://...)', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Rikiavimo eilė (mažesnis = pirmas)')),
                ('is_active', models.BooleanField(default=True, help_text='Ar rodyti šią skaidrę?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero skaidrė',
                'verbose_name_plural': 'Hero skaidrės',
                'ordering': ['order', 'id'],
            },
        ),
    ]
