# Generated by Django 4.2.2 on 2026-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0022_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedescription',
            name='home_carousel_interval',
            field=models.PositiveIntegerField(default=6, help_text='Karuselės skaidrių keitimosi intervalas sekundėmis (pvz. 6)'),
        ),
    ]
