# Generated by Django 4.2.2 on 2026-09-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0023_carousel_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Puslapio pavadinimas', max_length=255)),
                ('slug', models.SlugField(help_text='Puslapio URL dalis (pvz. naujienos)', max_length=255, unique=True)),
                ('content', models.TextField(blank=True, help_text='Puslapio turinys (HTML formatu)')),
                ('is_published', models.BooleanField(default=True, help_text='Ar puslapis yra matomas?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Puslapis',
                'verbose_name_plural': 'Puslapiai',
                'ordering': ['-created_at'],
            },
        ),
    ]
