# Generated by Django 4.2.2 on 2026-09-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0024_custompage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedescription',
            name='tour_finish_btn',
            field=models.CharField(default='Pradėti darbą', max_length=100),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_finish_btn_en',
            field=models.CharField(blank=True, default='Get started', max_length=100),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_finish_desc',
            field=models.TextField(default='Sveikiname susipažinus su Orbigrow. Bet kada prireikus peržiūrėti šį turą iš naujo, jį rasite savo Profilio puslapyje.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_finish_desc_en',
            field=models.TextField(blank=True, default='Congratulations on exploring Orbigrow. If you ever need to replay this tour, you can find it in your Profile page.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_finish_title',
            field=models.CharField(default='Viskas paruošta!', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_finish_title_en',
            field=models.CharField(blank=True, default='All set!', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_request_desc',
            field=models.TextField(default='Norite sužinoti, kaip sekėsi įgyvendinti projektą ar užduotį? Spustelėkite šį mygtuką, pasirinkite kolegas bei klausimyną ir išsiųskite prašymą.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_request_desc_en',
            field=models.TextField(blank=True, default='Want to know how your project or task went? Click this button, choose colleagues and a questionnaire, and send a request.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_request_title',
            field=models.CharField(default='Prašykite įvertinimo', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_request_title_en',
            field=models.CharField(blank=True, default='Request feedback', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_results_desc',
            field=models.TextField(default='Jūsų asmeninė kompetencijų statistika: interaktyvus radaras, stiprybės, tobulintinos sritys bei AI sugeneruotos įžvalgos.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_results_desc_en',
            field=models.TextField(blank=True, default='Your personal skill statistics: interactive radar chart, strengths, areas for improvement, and AI-generated insights.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_results_title',
            field=models.CharField(default='Rezultatai ir tobulėjimas', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_results_title_en',
            field=models.CharField(blank=True, default='Results & Growth', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_send_desc',
            field=models.TextField(default='Pastebėjote puikų kolegos darbą ar pagalbą? Nelaukite prašymo – proaktyviai išreikškite padėką ar pateikite vertingų įžvalgų.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_send_desc_en',
            field=models.TextField(blank=True, default="Noticed great work or help from a teammate? Don't wait for a request – proactively show appreciation or share constructive insights."),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_send_title',
            field=models.CharField(default='Siųskite įvertinimą bet kada', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_send_title_en',
            field=models.CharField(blank=True, default='Send feedback anytime', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_tasks_desc',
            field=models.TextField(default='Čia matysite visus kolegų atsiųstus prašymus įvertinti jų darbą. Stebėkite terminus ir patogiai pildykite atsakymus.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_tasks_desc_en',
            field=models.TextField(blank=True, default='Here you will see all feedback requests sent to you by colleagues. Track deadlines and easily complete evaluations.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_tasks_title',
            field=models.CharField(default='Mano Užduotys', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_tasks_title_en',
            field=models.CharField(blank=True, default='My Tasks', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_team_desc',
            field=models.TextField(default='Komandos narių sąrašas ir jų profiliai. Galite tiesiogiai peržiūrėti bendradarbių atvirą informaciją bei siųsti jiems įvertinimus.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_team_desc_en',
            field=models.TextField(blank=True, default='List of team members and their profiles. You can view open teammate info and send them feedback directly.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_team_title',
            field=models.CharField(default='Mano Komanda', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_team_title_en',
            field=models.CharField(blank=True, default='My Team', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_welcome_btn',
            field=models.CharField(default='Pradėti turą', max_length=100),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_welcome_btn_en',
            field=models.CharField(blank=True, default='Start tour', max_length=100),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_welcome_desc',
            field=models.TextField(default='Tai jūsų komandos 360° grįžtamojo ryšio ir kompetencijų auginimo sistema. Skirkite 1 minutę susipažinti su svarbiausiomis funkcijomis.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_welcome_desc_en',
            field=models.TextField(blank=True, default="This is your team's 360° feedback and skill growth platform. Take 1 minute to explore the key features."),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_welcome_title',
            field=models.CharField(default='Sveiki atvykę į Orbigrow!', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='tour_welcome_title_en',
            field=models.CharField(blank=True, default='Welcome to Orbigrow!', max_length=255),
        ),
    ]
