# Generated by Django 4.2.2 on 2026-09-27 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0025_pagedescription_tour_finish_btn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Straipsnio pavadinimas', max_length=255)),
                ('slug', models.SlugField(help_text='URL dalis (pvz. ka-reiskia-360-vertinimas)', max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Trumpa santrauka (jei tuščia, bus sugeneruota automatiškai)')),
                ('content', models.TextField(blank=True, help_text='Straipsnio turinys (HTML formatu)')),
                ('featured_image', models.ImageField(blank=True, help_text='Viršelio nuotrauka', null=True, upload_to='blog/')),
                ('author_name', models.CharField(default='OrbiGrow komanda', help_text='Autoriaus vardas', max_length=150)),
                ('is_published', models.BooleanField(default=True, help_text='Ar straipsnis publikuotas?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Publikavimo data')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Peržiūrų skaičius')),
            ],
            options={
                'verbose_name': 'Tinklaraščio įrašas',
                'verbose_name_plural': 'Tinklaraščio įrašai',
                'ordering': ['-created_at'],
            },
        ),
    ]
