# Generated by Django 4.2.2 on 2026-09-27 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_has_completed_tour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedbackas', '0028_globalsettings_risk_radar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnoutSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload_rating', models.IntegerField(default=3, help_text='Darbo krūvis: 1 (lengvas) iki 5 (perdegimo lygis)')),
                ('energy_rating', models.IntegerField(default=3, help_text='Energijos lygis: 1 (išsekęs) iki 5 (pilnas energijos)')),
                ('stress_frequency', models.IntegerField(default=3, help_text='Streso dažnumas: 1 (retai) iki 5 (kasdien)')),
                ('recognition_rating', models.IntegerField(default=3, help_text='Pripažinimas: 1 (nevertinamas) iki 5 (labai vertinamas)')),
                ('retention_rating', models.IntegerField(default=3, help_text='Ateities perspektyva: 1 (noriu išeiti) iki 5 (planuoju likti ilgai)')),
                ('comment', models.TextField(blank=True, help_text='Neprivalomi darbuotojo komentarai ar pastebėjimai')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='burnout_responses', to='users.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burnout_responses', to='users.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burnout_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savijautos ir perdegimo anketa',
                'verbose_name_plural': 'Savijautos ir perdegimo anketos',
                'ordering': ['-created_at'],
            },
        ),
    ]
