# Generated by Django 4.2.2 on 2026-09-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0029_burnoutsurveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='burnoutsurveyresponse',
            name='contributing_factors',
            field=models.TextField(blank=True, help_text='Raktiniai žodžiai, prisidedantys prie savijautos (kableliu atskirti)'),
        ),
        migrations.AddField(
            model_name='burnoutsurveyresponse',
            name='mood_emoji',
            field=models.CharField(default='😐', help_text="Pasirinktas nuotaikos emotikon'as", max_length=10),
        ),
        migrations.AddField(
            model_name='burnoutsurveyresponse',
            name='visibility',
            field=models.CharField(choices=[('private', 'Tik sau – asmeninis dienoraštis'), ('manager', 'Vadovui – 1-on-1 pokalbiams'), ('anonymous', 'Anonimiškai – rizikos & pulso analizei')], default='anonymous', help_text='Anketos matomumo lygis', max_length=20),
        ),
    ]
