# Generated by Django 4.2.2 on 2026-09-27 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_profile_has_completed_tour'),
        ('feedbackas', '0030_add_mood_factors_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellbeingCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField(default=3, help_text='Nuotaika: 1 (labai blogai) iki 5 (puikiai)')),
                ('energy_level', models.IntegerField(default=5, help_text='Energijos lygis: 1 (visiškas išsekimas) iki 10 (pilnas energijos)')),
                ('stress_level', models.IntegerField(default=5, help_text='Streso lygis: 1 (visiškai ramus) iki 10 (maksimalus stresas)')),
                ('workload_level', models.IntegerField(default=3, help_text='Darbo krūvis: 1 (lengvas) iki 5 (perkrova)')),
                ('comment', models.TextField(blank=True, help_text='Neprivalomi darbuotojo komentarai ar pastebėjimai')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing_checkins', to='users.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wellbeing_checkins', to='users.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savijautos ir perdegimo anketa',
                'verbose_name_plural': 'Savijautos ir perdegimo anketos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BurnoutSurveyResponse',
        ),
    ]
