# Generated by Django 4.2.2 on 2026-09-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0032_wellbeingcheckin_contributing_factors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellbeingcheckin',
            name='engagement_meaning',
            field=models.IntegerField(default=3, help_text='Santykis su darbu ir prasmė: 1 (stipri apatija/cinizmas) iki 5 (labai įsitraukęs)'),
        ),
        migrations.AddField(
            model_name='wellbeingcheckin',
            name='exhaustion_level',
            field=models.IntegerField(default=3, help_text='Išsekimas ir atsigavimas: 1 (visiškas išsekimas) iki 5 (energingas ir pailsėjęs)'),
        ),
        migrations.AddField(
            model_name='wellbeingcheckin',
            name='workload_control',
            field=models.IntegerField(default=3, help_text='Darbo krūvis ir kontrolė: 1 (visiškai perkrautas) iki 5 (puikiai subalansuotas)'),
        ),
    ]
